## >> Hiring Experience <<

In [1]:
The File Contains hiring stats for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3
factors. HR will decide the salary. Given this data, you need to build a machine learning model for HR Development that can help them decide
salaries for future candidates. Using This predict salaries for following candidates.

2 yrs experience, 9 test score, 6 interview score 12 yrs experience, 10 test score 10 interview score.

SyntaxError: invalid syntax (3401198797.py, line 1)

In [2]:
!pip install Pandas


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install scikit-learn


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
!pip install linear


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
!pip install word2number


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [7]:
df=pd.read_csv('Hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
df.experience=df.experience.fillna('zero')

In [9]:
df.experience=df.experience.apply(w2n.word_to_num)

In [10]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [11]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())

In [12]:
df.round()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [13]:
df.rename(columns={'salary($)':'salary_in_dollars'}, inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  \
0           0               8.000000                           9   
1           0               8.000000                           6   
2           5               6.000000                           7   
3           2              10.000000                          10   
4           7               9.000000                           6   
5           3               7.000000                          10   
6          10               7.857143                           7   
7          11               7.000000                           8   

   salary_in_dollars  
0              50000  
1              45000  
2              60000  
3              65000  
4              70000  
5              62000  
6              72000  
7              80000

In [14]:
new_df=df.drop('salary_in_dollars',axis='columns')
new_df

experience  test_score(out of 10)  interview_score(out of 10)
0           0               8.000000                           9
1           0               8.000000                           6
2           5               6.000000                           7
3           2              10.000000                          10
4           7               9.000000                           6
5           3               7.000000                          10
6          10               7.857143                           7
7          11               7.000000                           8

In [15]:
salary_in_dollars=df.salary_in_dollars
salary_in_dollars

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary_in_dollars, dtype: int64

In [16]:
reg = linear_model.LinearRegression()

In [17]:
reg.fit(new_df,salary_in_dollars)

LinearRegression()

In [18]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [19]:
reg.fit_intercept

True

In [20]:
reg.intercept_

np.float64(17237.330313727172)

In [21]:
reg.predict([[2,9,6]])

C:\Users\SG\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

In [22]:
reg.predict([[12,10,10]])

C:\Users\SG\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])